exp:
  ym_for_t_nu: 1000
  t_for_ym_nu: 100
  nu_for_ym_t: 0.3
  traction_zone: [50, 100, 150, 200]
  youngs_modulus: [500, 1000, 1500, 2000]
  nu: [0.2, 0.25, 0.3, 0.4]
  seeds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  T_for_noisy_exp: 100.0
  E_for_noisy_exp: 1000.0
  nu_for_noisy_exp: 0.3
  seed_for_noisy_exp: 1
  noise_stds: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]