plot_parameters:
  implot: 6
  vmaxstrain: 0.15
  scale: 2
  step: 1
  T_for_plot: 100
  E_for_plot: 1000
  nu_for_plot: 0.3
  threshold_inf: 0
  threshold_sup: 150
  scatter_comparison: True
  plot_noise: True
  plot_reg: True

experiment:
  of_funcs: [fista, hs, farneback, ilk, tvl1]
  T: null
  E: null
  nu: null
  exp_ind: null
  image_id: null
  T_for_reg: 100.0
  E_for_reg: 1000.0
  nu_for_reg: 0.3
  factors_for_reg: [1.4, 1.2, 1, 0.8, 0.6, 0.5]
