micro_exp:
  of_funcs: [fista, hs]

  # Image 1:
  # im: 1
  # path: "/Users/josephinelahmani/Desktop/250213_Overnight 50Hz 25Vpp_pos2.tif"
  # vminpositions: 0.48
  # vmaxpositions: 0.58
  # qt: True
  # alphapositions: 0.3
  # active_contour: True
  # scale_flow: 0.5 
  # scale_traction: 5.0 

  # Image 2:
  im: 2
  path: "/Users/josephinelahmani/Desktop/images_matthieu/260225/WT_gels1p2/250225_WT_1p2CD100RGD_FastAcq_pos1.tif" 
  vminpositions: null
  vmaxpositions: null
  qt: False
  alphapositions: 0.5
  active_contour: False
  scale_flow: 0.5
  scale_traction: 10.0

  
  center_circle_seg: [120, 120]
  radius_circle_seg: 100
  alpha: [0.015, 0.008] 
  beta: [5, 7] 
  gamma: [0.0005, 0.0005]
  E: 1000.0
  nu: 0.3
  vmaxstrain: 0.4
  step_flow: 8
  step_traction: 1