
optical_flow:
  global_flow: False

  fista:
    num_iter: 300 # for synthetic exp : 150, for image 1 and 2: 300
    num_warp: 5
    alpha: 0.3 # for synthetic exp : 0.1, from image 1: 0.01, for image 2: 0.3
    beta: 0.8 # for synthetic exp : 0.8, from image 1: 0.2, for image 2: 0.1
    eps: 0.001
    num_pyramid: 10
    pyramid_downscale: 1.5
    pyramid_min_size: 16

  hs:
    num_iter: 300 # for synthetic exp : 150, for image 1 and 2: 300
    num_warp: 5
    alpha: 0.3 # for synthetic exp : 0.1, for image 1: 0.01, for image 2: 0.3
    eps: 0.001
    num_pyramid: 10
    pyramid_downscale: 1.5
    pyramid_min_size: 16
    w: 1

  farneback:
    winSize: 10
    pyrScale: 0.3
    numLevels: 11 
    fastPyramids: True 
    numIters: 5
    polyN: 5 
    polySigma: 2
    flags: 0

  tvl1:
    attachment: 25
    tightness: 0.5
    num_warp: 5 
    num_iter: 150
    tol: 0.0001 
    prefilter: False

  ilk:
    radius: 3
    num_warp: 5 
    gaussian: True 
    prefilter: True 