elastic_simu:
  t_end: 1
  num_time_steps: 2
  eta: 0
  ym_for_t_nu: 1000
  t_for_ym_nu: 100
  nu_for_ym_t: 0.3
  traction_zone: [50, 100, 150, 200]
  youngs_modulus: [500, 1000, 1500, 2000]
  nu: [0.2, 0.25, 0.3, 0.4]
  seeds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]